#!/bin/bash
# ──────────────────────────────────────────────────────────────────────────────
# Khayyam PDF Editor – Project Setup Script
# Run this once (and again after pulling updates) to:
#   1. Install dependencies (XcodeGen, MuPDF)
#   2. Generate Config/LocalPaths.xcconfig with correct Homebrew paths
#   3. Generate KhayyamPDFEditor.xcodeproj via XcodeGen
#   4. Open the project in Xcode
# ──────────────────────────────────────────────────────────────────────────────

set -e
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo ""
echo "🔧 Khayyam PDF Editor – Setup"
echo "────────────────────────────────"

# ── 1. Homebrew ───────────────────────────────────────────────────────────────
if ! command -v brew &>/dev/null; then
  echo "❌ Homebrew not found. Install it from https://brew.sh then re-run."
  exit 1
fi
BREW_PREFIX="$(brew --prefix)"
echo "✅ Homebrew found at $BREW_PREFIX"

# ── 2. XcodeGen ───────────────────────────────────────────────────────────────
if ! command -v xcodegen &>/dev/null; then
  echo "📦 Installing XcodeGen…"
  brew install xcodegen
else
  echo "✅ XcodeGen $(xcodegen --version)"
fi

# ── 3. MuPDF ──────────────────────────────────────────────────────────────────
if brew list mupdf &>/dev/null; then
  echo "✅ MuPDF already installed"
else
  echo "📦 Installing MuPDF (AGPL)…"
  brew install mupdf
fi

MUPDF_INCLUDE="$BREW_PREFIX/include"
MUPDF_LIB="$BREW_PREFIX/lib"

# Sanity-check the MuPDF headers are present
if [ ! -f "$MUPDF_INCLUDE/mupdf/fitz.h" ]; then
  echo "⚠️  MuPDF headers not found at $MUPDF_INCLUDE/mupdf/fitz.h"
  echo "   Run 'brew install mupdf' manually and retry."
  exit 1
fi
echo "✅ MuPDF headers: $MUPDF_INCLUDE/mupdf/"

# ── 4. Determine MuPDF linker flags ───────────────────────────────────────────
# Prefer static libs so the hardened runtime won't reject unsigned Homebrew dylibs.
# MuPDF source builds (1.24+) produce several archives and rely on system libs
# (FreeType, HarfBuzz, Brotli, OpenJPEG) that must be linked explicitly.

if [ -f "$MUPDF_LIB/libmupdf.a" ]; then
  echo "✅ MuPDF static lib: $MUPDF_LIB/libmupdf.a"

  # --- Collect all MuPDF sub-archives (libmupdf.a, libmupdf-third.a,
  #     libmupdf-pkcs7.a, libextract.a, etc.) ---
  MUPDF_STATIC_LIBS=""
  for candidate in \
      libmupdf.a \
      libmupdf-third.a \
      libmupdf-pkcs7.a \
      libextract.a; do
    f="$MUPDF_LIB/$candidate"
    if [ -f "$f" ]; then
      MUPDF_STATIC_LIBS="$MUPDF_STATIC_LIBS $f"
      echo "   + $candidate"
    fi
  done

  # --- Collect third-party static libs that MuPDF source builds use ---
  # MuPDF 1.24+ links FreeType, HarfBuzz, Brotli, OpenJPEG from the system
  # instead of bundling them, so they must be linked separately.
  EXTRA_STATIC=""
  for lib in \
      freetype \
      harfbuzz harfbuzz-subset \
      brotlidec brotlienc brotlicommon \
      openjp2 \
      jbig2dec \
      mujs \
      gumbo; do
    f="$MUPDF_LIB/lib${lib}.a"
    if [ -f "$f" ]; then
      EXTRA_STATIC="$EXTRA_STATIC $f"
      echo "   + lib${lib}.a"
    fi
  done

  MUPDF_LDFLAGS="$MUPDF_STATIC_LIBS $EXTRA_STATIC -lm -lpthread -lz -liconv"

elif [ -f "$MUPDF_LIB/libmupdf.dylib" ]; then
  echo "⚠️  Only libmupdf.dylib found — linking dynamically."
  echo "   For a self-contained build, compile MuPDF from source (make install)."
  MUPDF_LDFLAGS="-lmupdf -lm -lpthread"
  MUPDF_EMBED_DYLIB="YES"
else
  echo "❌ Cannot find libmupdf.a or libmupdf.dylib in $MUPDF_LIB"
  echo "   Compile MuPDF from source: cd /tmp/mupdf-*-source && make install"
  exit 1
fi

# ── 5. Generate LocalPaths.xcconfig ───────────────────────────────────────────
mkdir -p Config
cat > Config/LocalPaths.xcconfig << EOF
// Auto-generated by setup.sh — do not edit manually, run ./setup.sh to regenerate
HOMEBREW_PREFIX = $BREW_PREFIX
MUPDF_HEADERS  = $MUPDF_INCLUDE
MUPDF_LIBS     = $MUPDF_LIB
MUPDF_LDFLAGS  = $MUPDF_LDFLAGS
EOF
echo "✅ Config/LocalPaths.xcconfig written"

# ── 6. Generate Xcode project ─────────────────────────────────────────────────
echo ""
echo "⚙️  Generating KhayyamPDFEditor.xcodeproj…"
xcodegen generate

# ── 7. Done ───────────────────────────────────────────────────────────────────
echo ""
echo "✅ Done! Opening project in Xcode…"
echo ""
open KhayyamPDFEditor.xcodeproj

echo "────────────────────────────────"
echo "Next steps:"
echo "  1. Select your Team in Signing & Capabilities"
echo "  2. Build & Run with ⌘R"
echo "  3. Open a PDF, then choose 'Edit Text' tool to edit existing text"
echo ""
echo "License note: MuPDF is AGPL — publishing this app requires"
echo "making the source code publicly available. ✅"
echo ""
